pycaf_web/blueprints/servers/__init__.py
#!/usr/bin/python
# -*- coding: utf8 -*-

from . import views

pycaf_web/blueprints/servers/views.py
#!/usr/bin/python
# -*- coding: utf8 -*-

from flask import Blueprint, render_template

blueprint = Blueprint('servers', __name__, template_folder='templates')

# A dictionary containing all imported servers
# TODO: find a better way to store theses
loaded_servers = dict()

def load_server(file_path):
    """
    Loads a pickled server from its filepath and inserts it in the loaded_servers dict.
    """
    print("Loading server.")
    with open(file_path, 'rb') as f:
        import pickle
        loaded_server = pickle.load(f)

    if loaded_server:
        global loaded_servers
        loaded_servers[loaded_server.uuid] = loaded_server
        return loaded_server.uuid

    return None

@blueprint.route('/get_server_from_uuid/<uuid>', methods=['GET'])
def get_server_from_uuid(uuid):
    """
    Parses the loaded_servers global to return server with uuid.
    """
    if uuid is None:
        return "Cannot get server with UUID: None."

    global loaded_servers
    for server_uuid in loaded_servers:
        if uuid == server_uuid:
            server = loaded_servers[uuid]
            #print("UUID neat: {}".format(server.uuid))
            #print("Infos are: {}".format(server.os_informations))
            #print("Modules are: {}".format(server.get_modules()))
            return render_template("servers/server_info.html", os_informations = server.os_informations,
                            server_id = server.uuid, modules=server.get_modules())

    return "Cannot find server with UUID: {}".format(uuid)

@blueprint.route('/list_servers')
def list_servers():
    """
    Lists all imported servers
    """
    print("Listing loaded servers")
    global loaded_servers

    return render_template('servers/list_servers.html', servers = loaded_servers)


@blueprint.route('/compare_servers', methods=['POST'])
def compare_servers():
    return "Not implemented yet"


@blueprint.route('/get_module_details/<uuid>/<module_name>', methods=['GET'])
def get_module_details(uuid, module_name):
    return render_template("servers/module_info.html", uuid=uuid, module_name=module_name)

pycaf_web/blueprints/servers/templates/servers/list_servers.html
{%- extends "base.html" %}

{% block content %}

<div class="container">

  <h2>Analyzed servers</h2>

  <div class="table-responsive">
    <form action="{{ url_for('servers.compare_servers') }}" method="POST">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Server UUID</th>
            <th>Type</th>
            <th>OS</th>
            <th>Version</th>
            <th>Architecture</th>
            <th>Select</th>
          </tr>
        </thead>
        <tbody>
          {% for uuid,server in servers.items() %}
          <tr>
            <td><a href="{{ url_for('servers.get_server_from_uuid', uuid=uuid) }}">{{ uuid }}</a></td>
            <td>{{ server.os_informations['system_type'] }}</td>
            <td>{{ server.os_informations['os'] }}</td>
            <td>{{ server.os_informations['version'] }}</td>
            <td>{{ server.os_informations['arch'] }}</td>
            <td><input type="checkbox" name="{{ uuid }}" value="{{ uuid }}"></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <input type="submit" value="Compare servers" class="btn btn-lg btn-default">
    </form>
  </div>

</div>

{%- endblock %}

pycaf_web/blueprints/servers/templates/servers/module_info.html
{%- extends "base.html" %}

{% block content %}

  <div class="container">
    <div class="jumbotron" align="center">
      <h2>Module: {{ module_name }}</h2>
    </div>
  </div>

{% endblock %}

pycaf_web/blueprints/servers/templates/servers/server_info.html
{%- extends "base.html" %}

{% block content %}

  <div class="container">
    <div class="jumbotron" align="center">
      <h2>Server UUID: {{ server_id }}</h2>
    </div>

    <h2>General</h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>OS Informations</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          {% for key,value in os_informations.items() %}
          <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <h2>Analyzed modules</h2>
    {% for module in modules %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Modules</th>
            <th>Improvements</th>
            <th>Warnings</th>
            <th>Criticals</th>
            <th>See details</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ module.name }}</td>
            <td>Work in progress...</td>
            <td>{{ url_for('servers.get_module_details', uuid=uuid, module_name=module.name) }}</td>
          </tr>
        </tbody>
      </table>
    {% endfor %}
    </ul>

  </div>

{% endblock %}