pycaf_web/blueprints/main/__init__.py
#!/usr/bin/python
# -*- coding: utf8 -*-

from . import views

pycaf_web/blueprints/main/views.py
#!/usr/bin/python
# -*- coding: utf8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask import current_app as app
from werkzeug.utils import secure_filename
import os

from pycaf_web.blueprints.servers.views import load_server, get_server_from_uuid
from pycaf2.pycaf import launch_pycaf

blueprint = Blueprint('main', __name__, template_folder='templates')

@blueprint.route('/', methods=['GET'])
def index():
    return render_template('main/index.html')

@blueprint.route('/import_server')
def import_server():
    return render_template('main/import_server.html')

@blueprint.route('/run_pycaf', methods=['GET'])
def run_pycaf():
    # Render
    return render_template('main/pycaf_launcher.html')


@blueprint.route('/import_and_run', methods=['POST'])
def import_and_run():
    """
    Get archive from input form, save it in the upload folder and run PyCAF.
    Redirect user on server details.
    """
    if "archive" not in request.files:
        return "No archive part in POST data"

    archive_file = request.files['archive']

    if archive_file.filename == '':
        return "No selected file"

    if allowed_file(archive_file.filename):
        filename = secure_filename(archive_file.filename)

        file_path = os.path.join (app.config['UPLOAD_FOLDER'], filename)
        archive_file.save(file_path)
        print("File has been uploaded here: {}".format(file_path))

        if not os.path.exists(file_path):
            return "Path {} does not exist.".format(file_path)

        # Run PyCAF !
        pickled_file = launch_pycaf(file_path, config_file=None, interactive=False, pickler=True, overwrite=True)
        if pickled_file:
            uuid = load_server(pickled_file)
            app.config['PICKLED_FILES'].append(pickled_file)
            return redirect( url_for('servers.get_server_from_uuid', uuid=uuid) )

        return "PyCAF analyzer has returned None, checkout debug logs."
    else:
        return "File extension is not allowed."


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']

pycaf_web/blueprints/main/templates/main/index.html
{%- extends "base.html" %}

{% block content %}
<script>
function notImplemented(){
  alert('Not implemented yet.')
}
</script>
  <div class="container">
    <div class="jumbotron" align="center">
      <h1>Welcome to PyCAF2-web</h1>
    </div>
    <div align="center">
      <p><b>Diclaimer</b>: this is a work in progress to understand how Flask and web can be useful to the PyCAF2 project.</p>
      <p>Please directly use the pycaf2 module with the command line if you want to run PyCAF2.</p>


      <a class="btn btn-lg btn-default" role="button" href="{{ url_for('servers.list_servers') }}">
        Browse imported servers
      </a>
      <p/>

      <p>
        <a class="btn btn-lg btn-default" role="button" href="{{ url_for('main.run_pycaf') }}">
          Launch PyCAF2 on server extract
        </a>
      </p>

    </div>

   </div>
{%- endblock %}

pycaf_web/blueprints/main/templates/main/pycaf_launcher.html
{%- extends "base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block content %}

<div class="container">

  <div align="center">
    <h2>Select your tar.gz archive:</h2>
    <form method=POST enctype=multipart/form-data action="{{ url_for('main.import_and_run') }}">
      <table class="table table-striped">
      <tr>
        <td><input id="archive" name="archive" type="file"></td>
        <td><input type="submit" value="Run PyCAF2!" class="btn btn-lg btn-default"></td>
      </tr>
      </table>
    </form>

  </div>

</div>



{%- endblock %}